#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Render client adapters from a project-local neutral orchestration contract."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
import os
from pathlib import Path
import re
import sys
import tempfile
from typing import Any

import yaml


SOURCE_ROOT = Path(".ai/orchestration")
MANIFEST_SCHEMA = "ai-project-orchestration/v1"
AGENT_SCHEMA = "ai-project-agent/v1"
COMMAND_SCHEMA = "ai-project-command/v1"
GENERATED_MARKER = "Generated by project-orchestration.py from .ai/orchestration/"
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
FORBIDDEN_NEUTRAL_TEXT = (
    "~/" + ".claude",
    "~/" + ".codex",
    ".claude/agents",
    ".claude/commands",
    ".codex/agents",
    ".agents/skills",
    "/" + "Users/",
    "/" + "Volumes/",
    "~/Library/" + "CloudStorage/",
)


class OrchestrationError(RuntimeError):
    """Raised when neutral sources or generated destinations are unsafe."""


@dataclass(frozen=True)
class GeneratedFile:
    path: Path
    content: bytes
    source: Path


def split_frontmatter(text: str, source: Path) -> tuple[dict[str, Any], str]:
    if not text.startswith("---\n"):
        raise OrchestrationError(f"{source} needs YAML frontmatter")
    parts = text.split("---\n", 2)
    if len(parts) != 3:
        raise OrchestrationError(f"{source} has unterminated YAML frontmatter")
    try:
        metadata = yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError as exc:
        raise OrchestrationError(f"{source} has invalid YAML: {exc}") from exc
    if not isinstance(metadata, dict):
        raise OrchestrationError(f"{source} frontmatter must be a mapping")
    return metadata, parts[2].lstrip("\n")


def load_yaml(path: Path) -> dict[str, Any]:
    if not path.is_file() or path.is_symlink():
        raise OrchestrationError(f"Missing regular orchestration manifest: {path}")
    try:
        value = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError) as exc:
        raise OrchestrationError(f"Invalid orchestration manifest {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise OrchestrationError(f"Orchestration manifest must be a mapping: {path}")
    return value


def validate_name(value: Any, label: str) -> str:
    name = str(value or "").strip()
    if not NAME_RE.fullmatch(name):
        raise OrchestrationError(f"{label} must use lowercase hyphen-case: {name!r}")
    return name


def require_string(metadata: dict[str, Any], key: str, source: Path) -> str:
    value = metadata.get(key)
    if not isinstance(value, str) or not value.strip():
        raise OrchestrationError(f"{source} needs a non-empty {key}")
    return value.strip()


def require_string_list(value: Any, label: str) -> list[str]:
    if not isinstance(value, list) or not value or any(
        not isinstance(item, str) or not item.strip() for item in value
    ):
        raise OrchestrationError(f"{label} must be a non-empty string list")
    return [item.strip() for item in value]


def validate_neutral_text(text: str, source: Path) -> None:
    for forbidden in FORBIDDEN_NEUTRAL_TEXT:
        if forbidden in text:
            raise OrchestrationError(
                f"{source} contains client- or machine-specific path {forbidden!r}"
            )
    slash_route = re.search(r"(?:^|[\s(])`?/[a-z][a-z0-9-]+`?(?=[\s.,):]|$)", text)
    if slash_route:
        raise OrchestrationError(
            f"{source} contains client-specific slash route {slash_route.group(0).strip()!r}"
        )


def execution_policy(metadata: dict[str, Any], source: Path) -> str:
    artifact = metadata.get("artifact_contract")
    writes = metadata.get("write_policy")
    capabilities = require_string_list(metadata.get("capabilities"), f"{source}: capabilities")
    if not isinstance(artifact, dict) or artifact.get("mode") not in {
        "response-only",
        "project-write",
    }:
        raise OrchestrationError(
            f"{source} needs artifact_contract.mode=response-only|project-write"
        )
    if not isinstance(writes, dict):
        raise OrchestrationError(f"{source} needs a write_policy mapping")
    project_write = writes.get("project")
    git_write = writes.get("git")
    if project_write not in {"read-only", "scoped-write"}:
        raise OrchestrationError(f"{source} has invalid write_policy.project")
    if git_write not in {"forbidden", "caller-authorized"}:
        raise OrchestrationError(f"{source} has invalid write_policy.git")
    if artifact["mode"] == "response-only" and project_write != "read-only":
        raise OrchestrationError(f"{source} response-only agent must be read-only")
    if artifact["mode"] == "project-write" and project_write != "scoped-write":
        raise OrchestrationError(f"{source} project-write agent needs scoped-write")

    project_line = {
        "read-only": "Treat project files as read-only.",
        "scoped-write": "Write only within the caller-approved project scope and this role's responsibilities.",
    }[project_write]
    git_line = {
        "forbidden": "Do not stage, commit, push, or otherwise mutate Git state.",
        "caller-authorized": "Mutate Git state only when the caller explicitly requests it.",
    }[git_write]
    artifact_line = {
        "response-only": "Return the result to the caller; do not create an undeclared durable artifact.",
        "project-write": "Project edits are the declared artifact; report the exact files changed.",
    }[artifact["mode"]]
    return (
        "## Execution contract (generated; mandatory)\n\n"
        f"- {artifact_line}\n"
        f"- {project_line}\n"
        f"- {git_line}\n"
        "- Read the active client's project guidance, then `.context/` and `.planning/` files that apply.\n"
        f"- Declared capabilities: {', '.join(sorted(set(capabilities)))}.\n\n"
    )


def render_agent(
    source: Path,
    project_root: Path,
    namespace: str,
) -> list[GeneratedFile]:
    text = source.read_text(encoding="utf-8")
    metadata, body = split_frontmatter(text, source)
    if metadata.get("schema") != AGENT_SCHEMA:
        raise OrchestrationError(f"{source} must declare schema: {AGENT_SCHEMA}")
    name = validate_name(metadata.get("name"), f"{source}: name")
    if source.stem != name:
        raise OrchestrationError(f"{source} filename must match agent name {name!r}")
    description = require_string(metadata, "description", source)
    validate_neutral_text(text, source)
    policy = execution_policy(metadata, source)
    adapter_name = f"{namespace}-{name}"
    if len(adapter_name) > 63:
        raise OrchestrationError(f"Generated agent name exceeds 63 characters: {adapter_name}")

    adapters = metadata.get("adapters")
    claude = adapters.get("claude") if isinstance(adapters, dict) else None
    if not isinstance(claude, dict):
        raise OrchestrationError(f"{source} needs adapters.claude")
    tools = require_string_list(claude.get("tools"), f"{source}: adapters.claude.tools")
    models = metadata.get("model_preferences")
    if models is not None and not isinstance(models, dict):
        raise OrchestrationError(f"{source} model_preferences must be a mapping")
    claude_model = str((models or {}).get("claude") or "sonnet")
    codex_model = str((models or {}).get("codex") or "default")

    claude_frontmatter = yaml.safe_dump(
        {
            "name": adapter_name,
            "description": description,
            "model": claude_model,
            "tools": tools,
        },
        sort_keys=False,
        allow_unicode=True,
    ).strip()
    claude_content = (
        f"---\n{claude_frontmatter}\n---\n\n"
        f"<!-- {GENERATED_MARKER}agents/{name}.md; do not edit. -->\n\n"
        f"{policy}{body}"
    ).encode("utf-8")

    instructions = policy + body
    if "'''" in instructions:
        raise OrchestrationError(f"{source} contains unsupported triple single quotes")
    sandbox_mode = (
        "read-only"
        if metadata["write_policy"]["project"] == "read-only"
        else "workspace-write"
    )
    codex_lines = [
        f"# {GENERATED_MARKER}agents/{name}.md; do not edit.",
        f"name = {json.dumps(adapter_name, ensure_ascii=False)}",
        f"description = {json.dumps(description, ensure_ascii=False)}",
        f"sandbox_mode = {json.dumps(sandbox_mode)}",
    ]
    if codex_model != "default":
        codex_lines.append(f"model = {json.dumps(codex_model)}")
    codex_lines.extend(
        [
            "developer_instructions = '''",
            instructions,
            "'''",
            "",
        ]
    )
    codex_content = "\n".join(codex_lines).encode("utf-8")
    return [
        GeneratedFile(
            project_root / ".claude/agents" / f"{adapter_name}.md",
            claude_content,
            source,
        ),
        GeneratedFile(
            project_root / ".codex/agents" / f"{adapter_name}.toml",
            codex_content,
            source,
        ),
    ]


def render_command(
    source: Path,
    project_root: Path,
    namespace: str,
    project_title: str,
) -> list[GeneratedFile]:
    text = source.read_text(encoding="utf-8")
    metadata, body = split_frontmatter(text, source)
    if metadata.get("schema") != COMMAND_SCHEMA:
        raise OrchestrationError(f"{source} must declare schema: {COMMAND_SCHEMA}")
    name = validate_name(metadata.get("name"), f"{source}: name")
    if source.stem != name:
        raise OrchestrationError(f"{source} filename must match command name {name!r}")
    description = require_string(metadata, "description", source)
    argument_hint = str(metadata.get("argument_hint") or "").strip()
    require_string_list(metadata.get("capabilities"), f"{source}: capabilities")
    validate_neutral_text(text, source)
    adapters = metadata.get("adapters")
    claude = adapters.get("claude") if isinstance(adapters, dict) else None
    if not isinstance(claude, dict):
        raise OrchestrationError(f"{source} needs adapters.claude")
    tools = require_string_list(
        claude.get("allowed_tools"),
        f"{source}: adapters.claude.allowed_tools",
    )
    adapter_name = f"{namespace}-{name}"
    if len(adapter_name) > 63:
        raise OrchestrationError(f"Generated skill name exceeds 63 characters: {adapter_name}")

    claude_metadata: dict[str, Any] = {
        "description": description,
        "allowed-tools": tools,
    }
    if argument_hint:
        claude_metadata["argument-hint"] = argument_hint
    claude_frontmatter = yaml.safe_dump(
        claude_metadata,
        sort_keys=False,
        allow_unicode=True,
    ).strip()
    claude_content = (
        f"---\n{claude_frontmatter}\n---\n\n"
        f"<!-- {GENERATED_MARKER}commands/{name}.md; do not edit. -->\n\n"
        f"# /{namespace}:{name}\n\n"
        f"Project workflow for **{project_title}**. Pass any request details as `$ARGUMENTS`.\n\n"
        f"{body}"
    ).encode("utf-8")

    skill_description = (
        f"{description} Use inside this repository when the user requests the "
        f"{name.replace('-', ' ')} project workflow."
    )
    codex_frontmatter = yaml.safe_dump(
        {"name": adapter_name, "description": skill_description},
        sort_keys=False,
        allow_unicode=True,
    ).strip()
    codex_content = (
        f"---\n{codex_frontmatter}\n---\n\n"
        f"<!-- {GENERATED_MARKER}commands/{name}.md; do not edit. -->\n\n"
        f"# Project workflow: {name}\n\n"
        f"This repository-scoped workflow applies to **{project_title}**. "
        "Treat the user's request after the skill name as the workflow arguments.\n\n"
        f"{body}"
    ).encode("utf-8")
    return [
        GeneratedFile(
            project_root / ".claude/commands" / namespace / f"{name}.md",
            claude_content,
            source,
        ),
        GeneratedFile(
            project_root / ".agents/skills" / adapter_name / "SKILL.md",
            codex_content,
            source,
        ),
    ]


def expected_files(project_root: Path) -> list[GeneratedFile]:
    source_root = project_root / SOURCE_ROOT
    manifest = load_yaml(source_root / "manifest.yaml")
    if manifest.get("schema") != MANIFEST_SCHEMA:
        raise OrchestrationError(
            f"{source_root / 'manifest.yaml'} must declare schema: {MANIFEST_SCHEMA}"
        )
    project_title = require_string(manifest, "project_title", source_root / "manifest.yaml")
    namespace = validate_name(manifest.get("namespace") or "project", "manifest namespace")
    validate_neutral_text(
        (source_root / "manifest.yaml").read_text(encoding="utf-8"),
        source_root / "manifest.yaml",
    )

    generated: list[GeneratedFile] = []
    agent_sources = sorted((source_root / "agents").glob("*.md"))
    command_sources = sorted((source_root / "commands").glob("*.md"))
    if not agent_sources:
        raise OrchestrationError(f"No neutral project agents found under {source_root / 'agents'}")
    if not command_sources:
        raise OrchestrationError(f"No neutral project commands found under {source_root / 'commands'}")
    for source in agent_sources:
        if source.is_symlink() or not source.is_file():
            raise OrchestrationError(f"Unsafe neutral agent source: {source}")
        generated.extend(render_agent(source, project_root, namespace))
    for source in command_sources:
        if source.is_symlink() or not source.is_file():
            raise OrchestrationError(f"Unsafe neutral command source: {source}")
        generated.extend(
            render_command(source, project_root, namespace, project_title)
        )
    if not any(path.source.stem == "update-state" for path in generated):
        raise OrchestrationError("Every orchestration contract must define commands/update-state.md")
    paths = [item.path for item in generated]
    if len(paths) != len(set(paths)):
        raise OrchestrationError("Neutral sources generate duplicate adapter paths")
    return generated


def ensure_safe_parent(path: Path, project_root: Path) -> None:
    try:
        relative = path.relative_to(project_root)
    except ValueError as exc:
        raise OrchestrationError(f"Generated path escapes the project: {path}") from exc
    current = project_root
    for part in relative.parent.parts:
        current = current / part
        if current.is_symlink():
            raise OrchestrationError(f"Refusing generated path below symlinked directory: {current}")
        if current.exists() and not current.is_dir():
            raise OrchestrationError(f"Generated parent is not a directory: {current}")
        if not current.exists():
            current.mkdir()


def atomic_write(path: Path, content: bytes, project_root: Path) -> None:
    ensure_safe_parent(path, project_root)
    if path.is_symlink() or (path.exists() and not path.is_file()):
        raise OrchestrationError(f"Refusing unsafe generated destination: {path}")
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
            temporary_name = handle.name
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary_name, 0o644)
        os.replace(temporary_name, path)
    finally:
        if temporary_name and os.path.exists(temporary_name):
            os.unlink(temporary_name)


def owned_generated_files(project_root: Path) -> set[Path]:
    candidates: set[Path] = set()
    patterns = (
        ".claude/agents/*.md",
        ".codex/agents/*.toml",
        ".claude/commands/*/*.md",
        ".agents/skills/*/SKILL.md",
    )
    for pattern in patterns:
        for path in project_root.glob(pattern):
            if path.is_file() and not path.is_symlink():
                try:
                    prefix = path.read_text(encoding="utf-8", errors="replace")[:600]
                except OSError:
                    continue
                if GENERATED_MARKER in prefix:
                    candidates.add(path)
    return candidates


def reconcile(project_root: Path, *, check: bool) -> tuple[list[str], int]:
    generated = expected_files(project_root)
    expected = {item.path: item for item in generated}
    changes: list[str] = []
    for path, item in sorted(expected.items(), key=lambda pair: str(pair[0])):
        if path.is_symlink() or (path.exists() and not path.is_file()):
            raise OrchestrationError(f"Refusing unsafe generated destination: {path}")
        current = path.read_bytes() if path.is_file() else None
        if current == item.content:
            continue
        if current is not None and GENERATED_MARKER.encode() not in current[:600]:
            raise OrchestrationError(
                f"Refusing to overwrite non-generated adapter {path}; reconcile it into {item.source} first"
            )
        changes.append(f"write:{path.relative_to(project_root)}")
        if not check:
            atomic_write(path, item.content, project_root)

    for path in sorted(owned_generated_files(project_root) - set(expected), key=str):
        changes.append(f"remove:{path.relative_to(project_root)}")
        if not check:
            path.unlink()
            parent = path.parent
            while parent != project_root and parent.is_dir():
                try:
                    parent.rmdir()
                except OSError:
                    break
                parent = parent.parent
    return changes, len(expected)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Render Claude Code and Codex project adapters from .ai/orchestration"
    )
    parser.add_argument("command", choices=("render", "check"))
    parser.add_argument("--project", default=".", help="Project root (default: current directory)")
    parser.add_argument("--json", action="store_true", help="Emit structured output")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    project_root = Path(args.project).expanduser().absolute()
    if not project_root.is_dir() or project_root.is_symlink():
        raise OrchestrationError(f"Project root must be a real directory: {project_root}")
    changes, expected_count = reconcile(project_root, check=args.command == "check")
    result = {
        "status": "drift" if changes and args.command == "check" else "current",
        "command": args.command,
        "project": str(project_root),
        "expected_adapters": expected_count,
        "changes": changes,
    }
    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True))
    elif changes:
        verb = "would change" if args.command == "check" else "changed"
        print(f"Project orchestration {verb} {len(changes)} adapter(s):")
        for change in changes:
            print(f"  {change}")
    else:
        print(f"Project orchestration current ({expected_count} adapters).")
    return 1 if args.command == "check" and changes else 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except OrchestrationError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(2)
